import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
import { IsNotEmpty, IsNumber, IsOptional, IsString } from 'class-validator';
import { PaymentStatus } from '../entities/payment.entity';

export class CreateSubscriptionDto {
  @ApiProperty({
    description: 'Stripe Email for the subscriber',
    example: 'john_dohe@gmail.com',
  })
  @IsString()
  @IsNotEmpty()
  email: string;

  @ApiProperty({ example: '4242424242424242', description: 'شماره کارت' })
  cardNumber: string;

  @ApiProperty({ example: '12/26', description: 'تاریخ انقضا (MM/YY)' })
  expDate: string;

  @ApiProperty({ example: '123', description: 'CVV کارت' })
  cvv: string;

  @ApiProperty({
    description: 'Stripe Price ID for the subscription plan',
    example: 'price_1R0ssRCQIZTVFLLFqYDDGQF4',
  })
  @IsString()
  @IsNotEmpty()
  priceId: string;

  @ApiPropertyOptional({
    description: 'Amount to be charged (optional, typically set in Stripe)',
    example: 9999,
  })
  @IsNumber()
  @IsOptional()
  amount?: number;

  @ApiPropertyOptional({
    description: 'Status of the payment',
    enum: PaymentStatus,
    example: PaymentStatus.Pending,
  })
  @IsOptional()
  payment_status?: PaymentStatus;

  @ApiPropertyOptional({
    description: 'Unique transaction ID generated by Stripe',
    example: 'txn_1234567890abcdef',
  })
  @IsString()
  @IsOptional()
  transaction_id?: string;
}
